function createfigure2(data1, data2, data3, data4, data5, data6)
%CREATEFIGURE2(data1, data2, data3, data4, data5, data6)
%  DATA1:  histogram data
%  DATA2:  histogram data
%  DATA3:  histogram data
%  DATA4:  histogram data
%  DATA5:  histogram data
%  DATA6:  histogram data

%  Auto-generated by MATLAB on 16-Dec-2019 16:05:48

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
h = histogram(data1,'DisplayName','Initial Distribution','Parent',axes1,...
    'FaceAlpha',1,...
    'FaceColor',[0.717647058823529 0.192156862745098 0.172549019607843],...
    'BinWidth',51);

% Create histogram
h = histogram(data2,'DisplayName','\alpha = 50','Parent',axes1,...
    'FaceAlpha',1,...
    'FaceColor',[0.949019607843137 0.662745098039216 0],...
    'BinWidth',45);

% Create histogram
h = histogram(data3,'DisplayName','\alpha = 20','Parent',axes1,...
    'FaceAlpha',1,...
    'FaceColor',[0.27843137254902 0.63921568627451 0.250980392156863],...
    'BinWidth',37);

% Create histogram
h = histogram(data4,'DisplayName','\alpha = 10','Parent',axes1,...
    'FaceAlpha',1,...
    'FaceColor',[0.388235294117647 0.396078431372549 0.411764705882353],...
    'BinWidth',22);

% Create histogram
h = histogram(data5,'DisplayName','\alpha = 5','Parent',axes1,...
    'FaceAlpha',1,...
    'FaceColor',[0.443137254901961 0.313725490196078 0.568627450980392],...
    'NumBins',15);

% Create histogram
h = histogram(data6,'DisplayName','\alpha = 3','Parent',axes1,...
    'FaceAlpha',1,...
    'FaceColor',[0 0.658823529411765 0.87843137254902],...
    'NumBins',15);

% Create ylabel
ylabel('Detached Mass [Pixel]');

% Create xlabel
xlabel('Grain Size [Pixel]');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16);
% Create legend
legend(axes1,'show');

