function createfigure2(data1, data2, data3, data4, data5, data6)
%CREATEFIGURE2(data1, data2, data3, data4, data5, data6)
%  DATA1:  histogram data
%  DATA2:  histogram data
%  DATA3:  histogram data
%  DATA4:  histogram data
%  DATA5:  histogram data
%  DATA6:  histogram data

%  Auto-generated by MATLAB on 16-Dec-2019 16:05:48

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
BinWidth = 51;
[Y, X] = histcounts(data1,'BinWidth',BinWidth);
Y = [0 Y 0];
X = [0 X + BinWidth/2];
xq = 0:1:max(X);
vq2 = interp1(X,Y,xq,'pchip');
plot(xq,vq2,...
    'DisplayName','Initial Distribution',...
    'Color',[0.717647058823529 0.192156862745098 0.172549019607843]...
    ,'LineWidth',2.5);

% Create histogram
BinWidth = 45;
[Y, X] = histcounts(data2,'BinWidth',BinWidth);
Y = [0 Y 0];
X = [0 X + BinWidth/2];
xq = 0:1:max(X);
vq2 = interp1(X,Y,xq,'pchip');
plot(xq,vq2,...
    'DisplayName','\alpha = 50',...
    'Color',[0.949019607843137 0.662745098039216 0]...
    ,'LineWidth',2.5);
% Create histogram
BinWidth = 37;
[Y, X] = histcounts(data3,'BinWidth',BinWidth);
Y = [0 Y 0];
X = [0 X + BinWidth/2];
xq = 0:1:max(X);
vq2 = interp1(X,Y,xq,'pchip');
plot(xq,vq2,...
    'DisplayName','\alpha = 20',...
    'Color',[0.27843137254902 0.63921568627451 0.250980392156863]...
    ,'LineWidth',2.5);
% Create histogram
BinWidth = 22;
[Y, X] = histcounts(data4,'BinWidth',BinWidth);
Y = [0 Y 0];
X = [0 X + BinWidth/2];
xq = 0:1:max(X);
vq2 = interp1(X,Y,xq,'pchip');
plot(xq,vq2,...
    'DisplayName','\alpha = 10',...
    'Color',[0.388235294117647 0.396078431372549 0.411764705882353]...
    ,'LineWidth',2.5);
% Create histogram
BinWidth = 15;
[Y, X] = histcounts(data5,'BinWidth',BinWidth);
Y = [0 Y 0];
X = [0 X + BinWidth/2];
xq = 0:1:max(X);
vq2 = interp1(X,Y,xq,'pchip');
plot(xq,vq2,...
    'DisplayName','\alpha = 5',...
    'Color',[0.443137254901961 0.313725490196078 0.568627450980392]...
    ,'LineWidth',2.5);
% Create histogram
BinWidth = 15;
[Y, X] = histcounts(data6,'BinWidth',BinWidth);
Y = [0 Y 0];
X = [0 X + BinWidth/2];
xq = 0:1:max(X);
vq2 = interp1(X,Y,xq,'pchip');
plot(xq,vq2,...
    'DisplayName','\alpha = 3',...
    'Color',[0 0.658823529411765 0.87843137254902]...
    ,'LineWidth',2.5);
% Create ylabel
ylabel('Detached Mass [Pixel]');


% Create xlabel
xlabel('Grain Size [Pixel]');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',18);
% Create legend
legend(axes1,'show');
