function createfigureinterp(initial, final, BinWidth, N)
%CREATEFIGURE2(data1, data2, data3, data4, data5, data6)
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 16-Dec-2019 16:05:48

% Create figure
figure1 = figure;

% Create axes

% Create histogram
axes1 = subplot(2,1,1);
hold on;
RedColor = [0.717647058823529 0.192156862745098 0.172549019607843];
[Y, X] = histcounts(initial,'BinWidth',BinWidth);
Y = [0 Y 0]/N;
X = [0 X + round(BinWidth/2)];
XMaxInitial = max(X);
YMaxInitial = max(Y);
xq = 0:1:XMaxInitial;
vq2 = interp1(X,Y,xq,'pchip');
plot(xq,vq2,...
    'DisplayName','Initial Distribution',...
    'Color',RedColor...
    ,'LineWidth',2.5);

% Plot mean and sigma
Mu = mean(initial);
MuYValue = mean(vq2(abs(Mu-xq)<1));
plot([Mu Mu],[0 MuYValue]...
    ,'Color',RedColor...
    ,'LineWidth',2 ...
    ,'LineStyle','--');
text(Mu,MuYValue,'\mu_0','Color',RedColor,'FontSize',18,'VerticalAlignment','Bottom','HorizontalAlignment','left');

Std = std(initial);
XStd = xq((Mu-Std < xq) & (xq < Mu+Std));
YStd = vq2((Mu-Std < xq) & (xq < Mu+Std));
area(XStd, YStd, 'FaceAlpha',0.2, 'FaceColor',RedColor,'LineStyle','none');

% Create histogram
axes2 = subplot(2,1,2);
hold on;
BlackColor = [0.388235294117647 0.396078431372549 0.411764705882353];
[Y, X] = histcounts(final,'BinWidth',BinWidth);
Y = [0 Y 0]/N;
X = [0 X + BinWidth/2];
xq = 0:1:max(X);
vq2 = interp1(X,Y,xq,'pchip');
plot(xq,vq2,...
    'DisplayName','Final Distribution',...
    'Color',BlackColor...
    ,'LineWidth',2.5);
Mu = mean(final);
MuYValue = mean(vq2(abs(Mu-xq)<1));
plot([Mu Mu],[0 MuYValue]...
    ,'Color',BlackColor...
    ,'LineWidth',2 ...
    ,'LineStyle','--');
text(Mu,MuYValue,'\mu_d','Color',BlackColor,'FontSize',18,'VerticalAlignment','Bottom','HorizontalAlignment','left');

Std = std(initial);
XStd = xq((Mu-Std < xq) & (xq < Mu+Std));
YStd = vq2((Mu-Std < xq) & (xq < Mu+Std));
area(XStd, YStd, 'FaceAlpha',0.3, 'FaceColor',BlackColor,'LineStyle','none');

box(axes1,'on');
% Create ylabel
ylabel(axes1,'Initial Area [Pixel]');
% Set the remaining axes properties
set(axes1,'FontSize',18);
xlim(axes1, [0 XMaxInitial + XMaxInitial/6]);
ylim(axes1, [0 YMaxInitial + YMaxInitial/6]);

box(axes2,'on');
% Create ylabel
ylabel(axes2,'Detached Area [Pixel]');
% Create xlabel
xlabel(axes2,'Particle Size [Pixel]');
% Set the remaining axes properties
set(axes2,'FontSize',18);
xlim(axes2, [0 XMaxInitial + XMaxInitial/6]);
ylim(axes2, [0 YMaxInitial + YMaxInitial/6]);
