function createfigureinterp2(initial, final, BinWidth, N)
%CREATEFIGURE2(data1, data2, data3, data4, data5, data6)
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 16-Dec-2019 16:05:48

% Create figure
figure1 = figure;

% Create axes

% Create histogram
hold on;
RedColor = [0.717647058823529 0.192156862745098 0.172549019607843];
[Y, X] = histcounts(initial,'BinWidth',BinWidth);
Y = [0 Y 0]/N;
X = [0 X + round(BinWidth/2)];
XMaxInitial = max(X);
YMaxInitial = max(Y);
xq = 0:1:XMaxInitial;
vq2 = interp1(X,Y,xq,'pchip');
plot(xq,vq2,...
    'DisplayName','Initial Distribution',...
    'Color',RedColor...
    ,'LineWidth',2.5);

% Plot mean and sigma
Mu = mean(initial);
MuYValue = mean(vq2(abs(Mu-xq)<1));
plot([Mu Mu],[0 MuYValue]...
    ,'DisplayName','\mu_0'...
    ,'Color',RedColor...
    ,'LineWidth',2 ...
    ,'LineStyle','--');
text(Mu,MuYValue,'\mu_0','Color',RedColor,'FontSize',24,'VerticalAlignment','Bottom','HorizontalAlignment','right');

Std = std(initial);
XStd = xq((Mu-Std < xq) & (xq < Mu+Std));
YStd = vq2((Mu-Std < xq) & (xq < Mu+Std));
area(XStd, YStd, 'FaceAlpha',0.2, 'FaceColor',RedColor,'LineStyle','none','DisplayName','\sigma_0');

% Create histogram
BlackColor = [0.388235294117647 0.396078431372549 0.411764705882353];
[Y, X] = histcounts(final,'BinWidth',BinWidth);
Y = [0 Y 0]/N;
X = [0 X + BinWidth/2];
xq = 0:1:max(X);
vq2 = interp1(X,Y,xq,'pchip');
plot(xq,vq2,...
    'DisplayName','Final Distribution',...
    'Color',BlackColor...
    ,'LineWidth',2.5);
Mu = mean(final);
MuYValue = mean(vq2(abs(Mu-xq)<1));
plot([Mu Mu],[0 MuYValue]...
    ,'DisplayName','\mu_d'...
    ,'Color',BlackColor...
    ,'LineWidth',2 ...
    ,'LineStyle','--');
text(Mu,MuYValue,'\mu_d','Color',BlackColor,'FontSize',24,'VerticalAlignment','Bottom','HorizontalAlignment','right');

Std = std(initial);
XStd = xq((Mu-Std < xq) & (xq < Mu+Std));
YStd = vq2((Mu-Std < xq) & (xq < Mu+Std));
area(XStd, YStd, 'FaceAlpha',0.3, 'FaceColor',BlackColor,'LineStyle','none','DisplayName','\sigma_d');

% Create ylabel
ylabel('Normalized mass [Pixel]','FontSize',18);
% Create xlabel
xlabel('Particle diameter [Pixel]','FontSize',18);
% Set the remaining axes properties
set(gca,'FontSize',18);
ylim([0 YMaxInitial + YMaxInitial/10]);
legend('Location','Best');