function createfigure4_2(X1, Y1, Y2, Y3, E1, E2, E3,T1,T2,T3)
%CREATEFIGURE4(X1, Y1, Y2, Y3)
%  X1:  scatter x
%  Y1:  scatter y
%  Y2:  scatter y
%  Y3:  scatter y

%  Auto-generated by MATLAB on 23-Dec-2019 13:55:18

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');
yyaxis left
%scatter(X1,Y1,'Parent',subplot1,'MarkerFaceColor',[0 0 1],...
 %   'MarkerEdgeColor',[0 0 1]);
errorbar(X1,Y1,E1,'o','MarkerSize',6,'MarkerFaceColor',[0 0 0],...
    'MarkerEdgeColor',[0 0 0],'Color',[0 0 0],'DisplayName','\mu_0=2160 rate');
set(subplot1,'FontSize',20,'Ycolor','k');
ylim([min(min([Y1 Y2 Y3]))-5,max(max([Y1 Y2 Y3]))+5]);
legend('Orientation','horizontal','Location','best','Box', 'off','AutoUpdate','off');
yyaxis right
scatter(X1,T1,'Parent',subplot1,'MarkerFaceColor',[1 0 1],...
    'MarkerEdgeColor',[1 0 1]);

ylim([min(min([T1 T2 T3]))-0.07,max(max([T1 T2 T3]))+0.07]);
% Set the remaining axes properties
box(subplot1,'on');
set(subplot1,'FontSize',20,'Ycolor',[1 0 1]);
xtickformat('percentage');

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);

hold(subplot2,'on');

% Create scatter
yyaxis left
errorbar(X1,Y2,E2,'o','MarkerSize',6,'MarkerFaceColor',[0 0 1],...
    'MarkerEdgeColor',[0 0 1],'Color',[0 0 1],'DisplayName','\mu_0=234 rate');
% Create ylabel
legend('Orientation','horizontal','Location','Best','Box', 'off','AutoUpdate','off');
set(subplot2,'FontSize',20,'Ycolor','b');
ylabel('Rate [Pixel/Step]','HorizontalAlignment','center','Color','k','FontSize',20);
ylim([min(min([Y1 Y2 Y3]))-5,max(max([Y1 Y2 Y3]))+5]);
yyaxis right
scatter(X1,T2,'Parent',subplot2,'MarkerFaceColor',[1 0 1],...
    'MarkerEdgeColor',[1 0 1]);
ylim([min(min([T1 T2 T3]))-0.07,max(max([T1 T2 T3]))+0.07]);
box(subplot2,'on');
ylabel('\tau factor','HorizontalAlignment','center');
% Set the remaining axes properties
set(subplot2,'FontSize',20,'Ycolor',[1 0 1]);
xtickformat('percentage');

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');
yyaxis left
% Create scatter
errorbar(X1,Y3,E3,'o','MarkerSize',6,'MarkerFaceColor',[1 0 0],...
    'MarkerEdgeColor',[1 0 0],'Color',[1 0 0],'DisplayName','\mu_0=108 rate');
% Create xlabel
legend('Orientation','horizontal','Location','best','Box', 'off');
set(subplot3,'FontSize',20,'Ycolor','r');
ylim([min(min([Y1 Y2 Y3]))-5,max(max([Y1 Y2 Y3]))+5]);
yyaxis right
scatter(X1,T3,'Parent',subplot3,'MarkerFaceColor',[1 0 1],...
    'MarkerEdgeColor',[1 0 1],'DisplayName','\tau factor');
ylim([min(min([T1 T2 T3]))-0.07,max(max([T1 T2 T3]))+0.07]);
xlabel('Offset','HorizontalAlignment','center');
box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontSize',20,'Ycolor',[1 0 1]);
xtickformat('percentage');
