function createfigure4(X1, Y1, Y2, Y3, E1, E2, E3)
%CREATEFIGURE4(X1, Y1, Y2, Y3)
%  X1:  scatter x
%  Y1:  scatter y
%  Y2:  scatter y
%  Y3:  scatter y

%  Auto-generated by MATLAB on 23-Dec-2019 13:55:18

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create scatter
errorbar(X1,Y1,E1,'o','Color',[0 0 0],'MarkerSize',8,'MarkerFaceColor',[0 0 0],...
   'MarkerEdgeColor',[0 0 0],'DisplayName','\mu_0=2160');
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',20);
xtickformat('percentage');
ylim([75 120]);
xlabel('Offset','HorizontalAlignment','center');
ylabel('Rate [Pixel/Step]','HorizontalAlignment','center');

legend('Location','northeast','Box', 'off');

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create scatter
errorbar(X1,Y2,E2,'o','Color',[0, 0, 0.75],'MarkerSize',8,'MarkerFaceColor',[0, 0, 0.75],...
   'MarkerEdgeColor',[0, 0, 0.75],'DisplayName','\mu_0=234');
% Create ylabel
xlabel('Offset','HorizontalAlignment','center');
ylabel('Rate [Pixel/Step]','HorizontalAlignment','center');

box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',20);
xtickformat('percentage');
ylim([75 120]);
legend('Orientation','horizontal','Location','northeast','Box', 'off');

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create scatter
errorbar(X1,Y3,E3,'o','Color',[.75, 0, 0],'MarkerSize',8,'MarkerFaceColor',[.75, 0, 0],...
   'MarkerEdgeColor',[.75, 0, 0],'DisplayName','\mu_0=108');
% Create xlabel
xlabel('Offset','HorizontalAlignment','center');
ylabel('Rate [Pixel/Step]','HorizontalAlignment','center');

box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontSize',20);
xtickformat('percentage');
ylim([75 120]);
legend('Orientation','horizontal','Location','northeast','Box', 'off');
