function createfigure6(X1, YMatrix1)
%CREATEFIGURE6(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 06-Jan-2020 11:28:28

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.177734375 0.775 0.747265625]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Marker','o','Parent',axes1);
set(plot1(1),'DisplayName','\alpha = 3',...
    'MarkerFaceColor',[0.600000023841858 0.200000002980232 0],...
    'Color',[0.600000023841858 0.200000002980232 0]);
set(plot1(2),'DisplayName','\alpha = 5',...
    'MarkerFaceColor',[0 0.498039215803146 0],...
    'Color',[0 0.498039215803146 0]);
set(plot1(3),'DisplayName','\alpha = 10','MarkerFaceColor',[0 0 1],...
    'Color',[0 0 1]);
set(plot1(4),'DisplayName','\alpha = 20','MarkerFaceColor',[1 0 0],...
    'Color',[1 0 0]);
set(plot1(5),'DisplayName','\alpha = 50','MarkerFaceColor',[0 0 0],...
    'Color',[0 0 0]);

% Create ylabel
ylabel('\mu_d _[_p_i_x_e_l_]','HorizontalAlignment','center');

% Create xlabel
xlabel('\mu_0 _[_p_i_x_e_l_]','HorizontalAlignment','center');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Location', 'NorthWest');

