function createfigure6_colors2(X1, YMatrix1)
%CREATEFIGURE6(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 06-Jan-2020 11:28:28

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.177734375 0.775 0.747265625]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Marker','o','Parent',axes1);
set(plot1(6),'DisplayName','\alpha = 3',...
    'MarkerFaceColor',[0 0.658823529411765 0.87843137254902],...
    'Color',[0 0.658823529411765 0.87843137254902]);
set(plot1(5),'DisplayName','\alpha = 5',...
    'MarkerFaceColor',[0.443137254901961 0.313725490196078 0.568627450980392],...
    'Color',[0.443137254901961 0.313725490196078 0.568627450980392]);
set(plot1(4),'DisplayName','\alpha = 10',...
    'MarkerFaceColor',[0.388235294117647 0.396078431372549 0.411764705882353],...
    'Color',[0.388235294117647 0.396078431372549 0.411764705882353]);
set(plot1(3),'DisplayName','\alpha = 20',...
    'MarkerFaceColor',[0.27843137254902 0.63921568627451 0.250980392156863],...
    'Color',[0.27843137254902 0.63921568627451 0.250980392156863]);
set(plot1(2),'DisplayName','\alpha = 50',...
    'MarkerFaceColor',[0.949019607843137 0.662745098039216 0],...
    'Color',[0.949019607843137 0.662745098039216 0]);
set(plot1(1),'DisplayName','\alpha \rightarrow \infty',...
    'MarkerFaceColor',[0.717647058823529 0.192156862745098 0.172549019607843],...
    'Color',[0.717647058823529 0.192156862745098 0.172549019607843]);
% Create ylabel
%ylabel('\mu_d _[_p_i_x_e_l_]','HorizontalAlignment','center');
ylabel('Mean detachment grain size [pixels]','HorizontalAlignment','center','FontSize',18);

% Create xlabel
%xlabel('\mu_0 _[_p_i_x_e_l_]','HorizontalAlignment','center');
xlabel('Mean initial grain size [pixels]','HorizontalAlignment','center','FontSize',18);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',18);
% Create legend
legend1 = legend(axes1,'show','FontSize',18);
set(legend1,...
    'Location', 'NorthWest');

