function data = GetMeanGrainSize(RockType, alpha)
    %% Make connection to database
    conn = database('rockmodeling','Yoni','Yoni','Vendor','MYSQL','Server','localhost','PortNumber',3306);

    %% Execute query and fetch results
    data = fetch(conn,['select NumGrains, ' ...
        '	avg(power(ce.Area,2))/avg(ce.Area) as WeightedMean ' ...
        'from models m ' ...
        'join steps s ' ...
        '	on s.modelId = m._id ' ...
        'join chunkevents ce ' ...
        '	on ce.modelid = m._id and ce.stepid = s.stepid ' ...
        'where m.RockType = ' num2str(RockType) ' ' ...
        '	and abs(m.DoloPercent - ' num2str(alpha) ') < 0.001 ' ...
        '   and ce.Area > 10 ' ...
        'group by NumGrains order by NumGrains']);
    %% Close connection to database
    close(conn)

    %% Clear variables
    clear conn
end