function createfigure(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 16-Dec-2019 12:24:47

% Create figure
figure1 = figure;


% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');


% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'DisplayName','Mechanical Weathering',...
    'Color',[0.600000023841858 0.200000002980232 0]);
set(plot1(2),'DisplayName','Chemical Weathering',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(3),'DisplayName','Total Weathering','Color',[0 0 0]);

% Create ylabel
ylabel('Weathering Rate [Pixel/Step]','HorizontalAlignment','center');

% Create xlabel
xlabel({'\alpha',''},'HorizontalAlignment','center');

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-1 130]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',18,'YTickLabel',{'','20','40','60','80','100','120'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.701881723049828 0.756969700383417 0.183064511899025 0.123636360222643],'EdgeColor','None');

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.194531250000001 0.452296819787985 0.239062499999999 0.340989399293287]);
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'Parent',axes2,'LineWidth',2);
set(plot2(1),'Color',[0.600000023841858 0.200000002980232 0]);
set(plot2(2),'Color',[0 0.447058826684952 0.74117648601532]);
set(plot2(3),'Color',[0 0 0]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1 10]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 12]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'Color',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'FontSize',18,'XTick',[0 2 4 6 8 10]);
% Create line
annotation(figure1,'line',[0.137096774193548 0.194354838709677],...
    [0.247272727272727 0.794545454545454]);

% Create line
annotation(figure1,'line',[0.208064516129032 0.433870967741936],...
    [0.154545454545455 0.450909090909091]);

% Create rectangle
annotation(figure1,'rectangle',...
    [0.137096774193548 0.156363633133983 0.0709677419354839 0.0909090941387445]);

% Create textbox
annotation(figure1,'textbox',...
    [0.280365079365079 0.524734982332155 0.145031746031746 0.0579875092448017],...
    'String','\alpha_d \approx 3.5',...
    'LineStyle','none',...
    'FontSize',18,...
    'FitBoxToText','off');

% Create textarrow
annotation(figure1,'textarrow',[0.288095238095238 0.273015873015873],...
    [0.522968197879859 0.468045854219738]);



